server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启动态路由
      routes:
        - id: dept-provider-route
          uri: lb://dept-provider
          predicates:
            - Path=/provider/dept/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: gateway-9000
