server:
  port: 80
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: dept-consumer
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: dept-consumer-80
feign:
  hystrix:
    enabled: true